# Generated by Django 4.1.3 on 2022-11-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_name", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "owner_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("link", models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={"db_table": "owner", "managed": True,},
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_name", models.CharField(max_length=45)),
                ("link", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "person_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("race_id", models.IntegerField(blank=True, null=True)),
                ("location_id_birth", models.IntegerField(blank=True, null=True)),
                ("birth_date", models.DateTimeField(blank=True, null=True)),
                ("location_id_death", models.IntegerField(blank=True, null=True)),
                ("death_date", models.DateTimeField(blank=True, null=True)),
                ("status_id", models.IntegerField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poll.owner"
                    ),
                ),
            ],
            options={"db_table": "person", "managed": True,},
        ),
        migrations.CreateModel(
            name="RelationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type_name",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                (
                    "relation_type_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={"db_table": "relation", "managed": True,},
        ),
        migrations.CreateModel(
            name="PersonToPersonAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.IntegerField(blank=True, null=True)),
                ("relation_type_id", models.IntegerField()),
                ("action_start", models.DateTimeField(blank=True, null=True)),
                ("action_stop", models.DateTimeField(blank=True, null=True)),
                (
                    "other_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_person_id",
                        to="poll.person",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_person_id",
                        to="poll.person",
                    ),
                ),
            ],
            options={"db_table": "person_to_person_action", "managed": True,},
        ),
    ]
