# Generated by Django 4.1.3 on 2022-11-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="relationtype", table="relation_type",),
    ]
