# Generated by Django 4.1.3 on 2022-11-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0002_alter_relationtype_table"),
    ]

    operations = [
        migrations.DeleteModel(name="RelationType",),
        migrations.RemoveField(
            model_name="persontopersonaction", name="relation_type_id",
        ),
        migrations.AddField(
            model_name="persontopersonaction",
            name="relation_type",
            field=models.IntegerField(choices=[(1, 1), (2, 2), (0, 0)], default=1),
        ),
    ]
