# Generated by Django 4.1.3 on 2022-11-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0003_delete_relationtype_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="person", name="status_id",),
        migrations.AddField(
            model_name="person",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Freezed"), (1, "Free"), (2, "Busy")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="persontopersonaction",
            name="relation_type",
            field=models.IntegerField(choices=[(1, "Game"), (2, "Mission")]),
        ),
    ]
