# Generated by Django 4.1.3 on 2022-11-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0006_alter_persontopersonaction_other_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="owner_status",
            field=models.IntegerField(choices=[(1, "Free"), (0, "Busy")], default=1),
        ),
    ]
