# Generated by Django 4.1.3 on 2022-11-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0007_owner_owner_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="owner_status",
            field=models.CharField(
                choices=[("F", "Free"), ("B", "Busy")], default="F", max_length=1
            ),
        ),
    ]
