# Generated by Django 4.1.3 on 2022-11-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0009_alter_owner_owner_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="owner_status",
            field=models.CharField(
                choices=[("0", "Free"), ("1", "Busy"), (" ", "Без статуса")],
                default=" ",
                max_length=1,
            ),
        ),
    ]
