# Generated by Django 4.1.3 on 2022-11-26 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0010_alter_owner_owner_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persontopersonaction",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person",
                to="poll.person",
            ),
        ),
    ]
