# Generated by Django 4.1.3 on 2022-11-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0012_group_membership_delete_persontopersonaction_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="group", options={"managed": True},),
        migrations.AlterModelOptions(name="membership", options={"managed": True},),
        migrations.RenameField(
            model_name="group", old_name="name", new_name="group_name",
        ),
        migrations.AlterModelTable(name="group", table="group",),
        migrations.AlterModelTable(name="membership", table="membership",),
    ]
