# Generated by Django 4.1.3 on 2022-11-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0013_alter_group_options_alter_membership_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="group_name",
            field=models.CharField(default="group", max_length=128),
        ),
    ]
