# Generated by Django 4.1.3 on 2022-11-27 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("poll", "0014_alter_group_group_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "race_name",
                    models.CharField(
                        choices=[
                            ("0", "Эльф"),
                            ("1", "Ангел"),
                            ("2", "Феникс"),
                            ("3", "Дриада"),
                            ("4", "Демон"),
                            ("5", "Вампир"),
                            ("6", "Дроу"),
                            ("7", "Тень"),
                            ("8", "Арахнид"),
                            ("9", "Нежить"),
                            ("10", "Дракон"),
                            ("11", "Драконейт"),
                            ("12", "Оборотень"),
                            ("13", "Человек"),
                            ("14", "Гном"),
                            ("15", "Русал"),
                            ("16", "Зверин"),
                            ("17", "Звероподобное"),
                            ("18", "Змеелюд"),
                            ("19", "Метаморф"),
                            ("20", "Атлант"),
                            ("21", "Гоблин"),
                            ("22", "Орк"),
                        ],
                        default="13",
                        max_length=2,
                    ),
                ),
                (
                    "race_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("start_points", models.JSONField()),
                ("finish_points", models.JSONField()),
                ("start_resistanses", models.JSONField()),
                ("start_permissions", models.JSONField()),
                ("equipment", models.JSONField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "race", "managed": True,},
        ),
    ]
