# Generated by Django 4.1.3 on 2022-11-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0015_race"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="person",
            old_name="location_id_birth",
            new_name="location_birth",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="location_id_death",
            new_name="location_death",
        ),
        migrations.RemoveField(model_name="person", name="person_description",),
        migrations.RemoveField(model_name="person", name="race_id",),
        migrations.AddField(
            model_name="person",
            name="biography",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="character",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="interests",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="phobias",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="race",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
