# Generated by Django 4.1.3 on 2022-11-28 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0016_bar_rename_location_id_birth_person_location_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="race",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="poll.race"
            ),
        ),
    ]
