# Generated by Django 4.1.3 on 2022-12-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0016_fraction_location_alter_owner_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "action_alias",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "action_description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "action_result",
                    models.JSONField(blank=True, null=True, verbose_name="Результат"),
                ),
            ],
            options={
                "verbose_name": "Action",
                "verbose_name_plural": "Actions",
                "db_table": "action",
                "managed": True,
            },
        ),
    ]
