# Generated by Django 4.1.3 on 2022-11-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0017_alter_person_race"),
    ]

    operations = [
        migrations.AddField(
            model_name="race", name="lifetime", field=models.IntegerField(default=100),
        ),
    ]
