# Generated by Django 4.1.3 on 2022-11-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0018_race_lifetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="equipment",
            field=models.JSONField(verbose_name="Снаряжение"),
        ),
        migrations.AlterField(
            model_name="race",
            name="finish_points",
            field=models.JSONField(verbose_name="Предельные очки характеристик"),
        ),
        migrations.AlterField(
            model_name="race",
            name="lifetime",
            field=models.IntegerField(
                default=100, verbose_name="Продолжительность жизни"
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="start_permissions",
            field=models.JSONField(verbose_name="Стартовые очки навыков"),
        ),
        migrations.AlterField(
            model_name="race",
            name="start_points",
            field=models.JSONField(verbose_name="Стартовые очки характеристик"),
        ),
        migrations.AlterField(
            model_name="race",
            name="start_resistanses",
            field=models.JSONField(verbose_name="Стартовые очки сопротивлений"),
        ),
    ]
