# Generated by Django 4.1.3 on 2022-11-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0019_alter_race_equipment_alter_race_finish_points_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="race_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
