# Generated by Django 4.1.3 on 2022-11-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0020_alter_race_race_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="race_name",
            field=models.CharField(
                choices=[
                    ("0", "Эльф"),
                    ("1", "Ангел"),
                    ("2", "Феникс"),
                    ("3", "Дриада"),
                    ("4", "Демон"),
                    ("5", "Вампир"),
                    ("6", "Дроу"),
                    ("7", "Тень"),
                    ("8", "Арахнид"),
                    ("9", "Нежить"),
                    ("10", "Дракон"),
                    ("11", "Драконейт"),
                    ("12", "Оборотень"),
                    ("13", "Человек"),
                    ("14", "Гном"),
                    ("15", "Русал"),
                    ("16", "Зверин"),
                    ("17", "Звероподобное"),
                    ("18", "Змеелюд"),
                    ("19", "Метаморф"),
                    ("20", "Атлант"),
                    ("21", "Гоблин"),
                    ("22", "Орк"),
                ],
                default="13",
                max_length=20,
            ),
        ),
    ]
