# Generated by Django 4.1.3 on 2022-12-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0020_alter_action_ap_alter_action_bp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="action_points",
            field=models.JSONField(default={}, verbose_name="Характеристики"),
        ),
    ]
