# Generated by Django 4.1.3 on 2022-11-28 15:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0021_alter_race_race_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name="race",
            name="lifetime",
            field=models.IntegerField(
                default=100,
                help_text="Продолжительность жизни",
                verbose_name="Продолжительность жизни",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="race_description",
            field=models.TextField(
                blank=True, help_text="Описание", null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="start_points",
            field=models.JSONField(
                help_text="Стартовые очки характеристик",
                verbose_name="Стартовые очки характеристик",
            ),
        ),
    ]
