# Generated by Django 4.1.3 on 2022-12-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0022_alter_action_action_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="action_equipment",
            field=models.JSONField(default=dict, verbose_name="Снаряжение"),
        ),
        migrations.AlterField(
            model_name="action",
            name="action_permissions",
            field=models.JSONField(default=dict, verbose_name="Умения"),
        ),
        migrations.AlterField(
            model_name="action",
            name="action_resistanses",
            field=models.JSONField(default=dict, verbose_name="Сопротивляемость"),
        ),
    ]
