# Generated by Django 4.1.3 on 2022-11-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0022_post_alter_race_lifetime_alter_race_race_description_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Post",),
        migrations.AlterModelOptions(
            name="race", options={"managed": True, "ordering": ["race_name"]},
        ),
        migrations.AlterField(
            model_name="race",
            name="lifetime",
            field=models.IntegerField(
                default=100, verbose_name="Продолжительность жизни"
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="race_description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="race",
            name="start_points",
            field=models.JSONField(verbose_name="Стартовые очки характеристик"),
        ),
    ]
