# Generated by Django 4.1.3 on 2022-12-02 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0023_delete_post_alter_race_options_alter_race_lifetime_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fraction_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "fraction_description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
            ],
            options={"db_table": "fraction", "managed": True,},
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "location_description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
            ],
            options={"db_table": "location", "managed": True,},
        ),
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quest_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "quest_description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poll.location"
                    ),
                ),
            ],
            options={"db_table": "quest", "managed": True,},
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "party_description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poll.quest"
                    ),
                ),
            ],
            options={"db_table": "party", "managed": True,},
        ),
        migrations.CreateModel(
            name="FractionLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reputation", models.IntegerField(blank=True, null=True)),
                (
                    "fraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poll.fraction"
                    ),
                ),
                (
                    "other_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_location",
                        to="poll.location",
                    ),
                ),
            ],
            options={"db_table": "fraction_location", "managed": True,},
        ),
        migrations.CreateModel(
            name="FractionFraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reputation", models.IntegerField(blank=True, null=True)),
                (
                    "fraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poll.fraction"
                    ),
                ),
                (
                    "other_fraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_fraction",
                        to="poll.fraction",
                    ),
                ),
            ],
            options={"db_table": "fraction_fraction", "managed": True,},
        ),
        migrations.AddField(
            model_name="fraction",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="poll.location"
            ),
        ),
        migrations.CreateModel(
            name="Clan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clan_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "clan_description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "chief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poll.person"
                    ),
                ),
            ],
            options={"db_table": "clan", "managed": True,},
        ),
    ]
