# Generated by Django 4.1.3 on 2022-12-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0024_fraction_location_quest_party_fractionlocation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reputation", models.IntegerField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poll.location"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poll.person"
                    ),
                ),
            ],
            options={"db_table": "person_location", "managed": True,},
        ),
        migrations.CreateModel(
            name="PersonFraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reputation", models.IntegerField(blank=True, null=True)),
                (
                    "fraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poll.fraction"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poll.person"
                    ),
                ),
            ],
            options={"db_table": "person_fraction", "managed": True,},
        ),
    ]
