# Generated by Django 4.1.3 on 2022-12-02 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0025_personlocation_personfraction"),
    ]

    operations = [
        migrations.RemoveField(model_name="fraction", name="location",),
        migrations.AddField(
            model_name="fractionlocation",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="poll.location",
            ),
            preserve_default=False,
        ),
    ]
