# Generated by Django 4.1.3 on 2022-12-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0025_rename_polearm_acces_action_polearm_access_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="SP",
            field=models.IntegerField(default=0, max_length=3, verbose_name="Стамина"),
        ),
    ]
