# Generated by Django 4.1.3 on 2022-12-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0026_alter_action_sp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="SP",
            field=models.IntegerField(default=0, verbose_name="Стамина"),
        ),
    ]
