# Generated by Django 4.1.3 on 2022-12-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0028_alter_action_action_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="points",
            field=models.JSONField(
                default='{"SP": 0, "MP": 0, "IP": 0, "PP": 0, "AP": 0, "FP": 0, "LP": 0, "CP": 0, "BP": 0}',
                verbose_name="Характеристики",
            ),
        ),
    ]
