# Generated by Django 4.1.3 on 2022-12-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0030_alter_action_action_equipment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="equipment",
            field=models.JSONField(blank=True, null=True, verbose_name="Снаряжение"),
        ),
        migrations.AlterField(
            model_name="action",
            name="permissions",
            field=models.JSONField(blank=True, null=True, verbose_name="Умения"),
        ),
        migrations.AlterField(
            model_name="action",
            name="points",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Характеристики"
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="resistances",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Сопротивляемость"
            ),
        ),
    ]
