# Generated by Django 4.1.3 on 2022-12-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0031_alter_action_action_equipment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="race",
            old_name="start_resistanses",
            new_name="start_resistances",
        ),
    ]
