# Generated by Django 4.1.3 on 2022-12-14 17:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0032_rename_start_resistanses_race_start_resistances"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agg_points",
                    models.IntegerField(default=0, verbose_name="Характеристики"),
                ),
                (
                    "points",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Характеристики"
                    ),
                ),
                ("SP", models.IntegerField(default=0, verbose_name="Стамина")),
                ("MP", models.IntegerField(default=0, verbose_name="Колдовство")),
                ("IP", models.IntegerField(default=0, verbose_name="Интеллект")),
                ("PP", models.IntegerField(default=0, verbose_name="Сила")),
                ("AP", models.IntegerField(default=0, verbose_name="Ловкость")),
                ("FP", models.IntegerField(default=0, verbose_name="Вера")),
                ("LP", models.IntegerField(default=0, verbose_name="Удача")),
                ("CP", models.IntegerField(default=0, verbose_name="Харизма")),
                ("BP", models.IntegerField(default=0, verbose_name="Рассудок")),
                (
                    "resistances",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Устойчивость"
                    ),
                ),
                ("fire_res", models.IntegerField(default=0, verbose_name="к огню")),
                ("water_res", models.IntegerField(default=0, verbose_name="к воде")),
                ("wind_res", models.IntegerField(default=0, verbose_name="к ветру")),
                ("dirt_res", models.IntegerField(default=0, verbose_name="к земле")),
                (
                    "lightning_res",
                    models.IntegerField(default=0, verbose_name="к молниям"),
                ),
                ("holy_res", models.IntegerField(default=0, verbose_name="к свету")),
                ("curse_res", models.IntegerField(default=0, verbose_name="к тьме")),
                (
                    "crush_res",
                    models.IntegerField(default=0, verbose_name="к дроблению"),
                ),
                ("cut_res", models.IntegerField(default=0, verbose_name="к порезам")),
                (
                    "stab_res",
                    models.IntegerField(default=0, verbose_name="к протыканию"),
                ),
                (
                    "permissions",
                    models.JSONField(blank=True, null=True, verbose_name="Навыки"),
                ),
                (
                    "Fire_access",
                    models.IntegerField(default=0, verbose_name="Пирокинектика"),
                ),
                (
                    "Water_access",
                    models.IntegerField(default=0, verbose_name="Гидрософистика"),
                ),
                (
                    "Wind_access",
                    models.IntegerField(default=0, verbose_name="Аэрософистика"),
                ),
                (
                    "Dirt_access",
                    models.IntegerField(default=0, verbose_name="Геомантия"),
                ),
                (
                    "Lightning_access",
                    models.IntegerField(default=0, verbose_name="Киловактика"),
                ),
                (
                    "Holy_access",
                    models.IntegerField(default=0, verbose_name="Элафристика"),
                ),
                (
                    "Curse_access",
                    models.IntegerField(default=0, verbose_name="Катифристика"),
                ),
                (
                    "Bleed_access",
                    models.IntegerField(default=0, verbose_name="Гематомантия"),
                ),
                (
                    "Nature_access",
                    models.IntegerField(default=0, verbose_name="Ботаника"),
                ),
                (
                    "Mental_access",
                    models.IntegerField(default=0, verbose_name="Псифистика"),
                ),
                (
                    "Twohanded_access",
                    models.IntegerField(default=0, verbose_name="Двуручное оружие"),
                ),
                (
                    "Polearm_access",
                    models.IntegerField(default=0, verbose_name="Древковое оружие"),
                ),
                (
                    "Onehanded_access",
                    models.IntegerField(default=0, verbose_name="Одноручное оружие"),
                ),
                (
                    "Stabbing_access",
                    models.IntegerField(default=0, verbose_name="Колющее оружие"),
                ),
                (
                    "Cutting_access",
                    models.IntegerField(default=0, verbose_name="Режущее оружие"),
                ),
                (
                    "Crushing_access",
                    models.IntegerField(default=0, verbose_name="Дробящее оружие"),
                ),
                (
                    "Small_arms_access",
                    models.IntegerField(default=0, verbose_name="Стрелковое оружие"),
                ),
                ("Shields_access", models.IntegerField(default=0, verbose_name="Щиты")),
                (
                    "equipment",
                    models.JSONField(blank=True, null=True, verbose_name="Снаряжение"),
                ),
                ("helmet_status", models.IntegerField(default=0, verbose_name="Шлем")),
                (
                    "chest_status",
                    models.IntegerField(default=0, verbose_name="Нагрудник"),
                ),
                ("shoes_status", models.IntegerField(default=0, verbose_name="Сапоги")),
                (
                    "gloves_status",
                    models.IntegerField(default=0, verbose_name="Наручи"),
                ),
                ("item_status", models.IntegerField(default=0, verbose_name="Прочее")),
                ("fov", models.IntegerField(default=0, verbose_name="Поле зрения")),
                (
                    "rov",
                    models.IntegerField(default=0, verbose_name="Область видимости"),
                ),
                (
                    "feature_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "feature_description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
                "db_table": "feature",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="action",
            name="fov",
            field=models.IntegerField(default=0, verbose_name="Поле зрения"),
        ),
        migrations.AddField(
            model_name="action",
            name="rov",
            field=models.IntegerField(default=0, verbose_name="Область видимости"),
        ),
        migrations.AlterField(
            model_name="action",
            name="Crushing_access",
            field=models.IntegerField(default=0, verbose_name="Дробящее оружие"),
        ),
        migrations.AlterField(
            model_name="action",
            name="Cutting_access",
            field=models.IntegerField(default=0, verbose_name="Режущее оружие"),
        ),
        migrations.AlterField(
            model_name="action",
            name="Onehanded_access",
            field=models.IntegerField(default=0, verbose_name="Одноручное оружие"),
        ),
        migrations.AlterField(
            model_name="action",
            name="Polearm_access",
            field=models.IntegerField(default=0, verbose_name="Древковое оружие"),
        ),
        migrations.AlterField(
            model_name="action",
            name="Shields_access",
            field=models.IntegerField(default=0, verbose_name="Щиты"),
        ),
        migrations.AlterField(
            model_name="action",
            name="Small_arms_access",
            field=models.IntegerField(default=0, verbose_name="Стрелковое оружие"),
        ),
        migrations.AlterField(
            model_name="action",
            name="Stabbing_access",
            field=models.IntegerField(default=0, verbose_name="Колющее оружие"),
        ),
        migrations.AlterField(
            model_name="action",
            name="Twohanded_access",
            field=models.IntegerField(default=0, verbose_name="Двуручное оружие"),
        ),
        migrations.AlterField(
            model_name="action",
            name="action_description",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="crush_res",
            field=models.IntegerField(default=0, verbose_name="к дроблению"),
        ),
        migrations.AlterField(
            model_name="action",
            name="curse_res",
            field=models.IntegerField(default=0, verbose_name="к тьме"),
        ),
        migrations.AlterField(
            model_name="action",
            name="cut_res",
            field=models.IntegerField(default=0, verbose_name="к порезам"),
        ),
        migrations.AlterField(
            model_name="action",
            name="dirt_res",
            field=models.IntegerField(default=0, verbose_name="к земле"),
        ),
        migrations.AlterField(
            model_name="action",
            name="fire_res",
            field=models.IntegerField(default=0, verbose_name="к огню"),
        ),
        migrations.AlterField(
            model_name="action",
            name="holy_res",
            field=models.IntegerField(default=0, verbose_name="к свету"),
        ),
        migrations.AlterField(
            model_name="action",
            name="lightning_res",
            field=models.IntegerField(default=0, verbose_name="к молниям"),
        ),
        migrations.AlterField(
            model_name="action",
            name="permissions",
            field=models.JSONField(blank=True, null=True, verbose_name="Навыки"),
        ),
        migrations.AlterField(
            model_name="action",
            name="resistances",
            field=models.JSONField(blank=True, null=True, verbose_name="Устойчивость"),
        ),
        migrations.AlterField(
            model_name="action",
            name="stab_res",
            field=models.IntegerField(default=0, verbose_name="к протыканию"),
        ),
        migrations.AlterField(
            model_name="action",
            name="water_res",
            field=models.IntegerField(default=0, verbose_name="к воде"),
        ),
        migrations.AlterField(
            model_name="action",
            name="wind_res",
            field=models.IntegerField(default=0, verbose_name="к ветру"),
        ),
        migrations.AlterField(
            model_name="owner",
            name="owner_description",
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="biography",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="character",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="interests",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="phobias",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="race",
            name="race_description",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
    ]
