# Generated by Django 4.1.3 on 2022-12-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0033_feature_action_fov_action_rov_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="fov",
            field=models.IntegerField(default=0, verbose_name="Область обзора"),
        ),
        migrations.AddField(
            model_name="race",
            name="rov",
            field=models.IntegerField(default=0, verbose_name="Дальность обзора"),
        ),
        migrations.AlterField(
            model_name="action",
            name="fov",
            field=models.IntegerField(default=0, verbose_name="Область обзора"),
        ),
        migrations.AlterField(
            model_name="action",
            name="rov",
            field=models.IntegerField(default=0, verbose_name="Дальность обзора"),
        ),
        migrations.AlterField(
            model_name="feature",
            name="fov",
            field=models.IntegerField(default=0, verbose_name="Область обзора"),
        ),
        migrations.AlterField(
            model_name="feature",
            name="rov",
            field=models.IntegerField(default=0, verbose_name="Дальность обзора"),
        ),
    ]
