# Generated by Django 4.1.3 on 2022-12-15 18:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0036_alter_owner_options_person_person_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location_description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="person_img",
            field=models.ImageField(default="media/euploads/python.png", upload_to=""),
        ),
        migrations.AlterField(
            model_name="race",
            name="race_description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
    ]
