# Generated by Django 4.1.3 on 2022-12-16 11:09

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0037_alter_location_location_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "zone_description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "zone",
                "verbose_name_plural": "Zones",
                "db_table": "zone",
                "ordering": ["zone_name"],
                "managed": True,
            },
        ),
        migrations.AlterField(
            model_name="action",
            name="action_alias",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Алиас"
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="action_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="link",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="owner_description",
            field=ckeditor.fields.RichTextField(
                blank=True, max_length=200, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="owner_img",
            field=models.ImageField(
                upload_to="media/euploads", verbose_name="Изображениеэ"
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="owner_name",
            field=models.CharField(
                blank=True, max_length=45, null=True, verbose_name="Игрок"
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="finish_points",
            field=models.JSONField(verbose_name="Максимальные характеристики"),
        ),
        migrations.AlterField(
            model_name="race",
            name="race_description",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="race_img",
            field=models.ImageField(
                default="media/python.png", upload_to="", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="race_name",
            field=models.CharField(
                choices=[
                    ("0", "Эльф"),
                    ("1", "Ангел"),
                    ("2", "Феникс"),
                    ("3", "Дриада"),
                    ("4", "Демон"),
                    ("5", "Вампир"),
                    ("6", "Дроу"),
                    ("7", "Тень"),
                    ("8", "Арахнид"),
                    ("9", "Нежить"),
                    ("10", "Дракон"),
                    ("11", "Драконейт"),
                    ("12", "Оборотень"),
                    ("13", "Человек"),
                    ("14", "Гном"),
                    ("15", "Русал"),
                    ("16", "Зверин"),
                    ("17", "Звероподобное"),
                    ("18", "Змеелюд"),
                    ("19", "Метаморф"),
                    ("20", "Атлант"),
                    ("21", "Гоблин"),
                    ("22", "Орк"),
                    ("23", "прочие"),
                ],
                default="13",
                max_length=20,
                verbose_name="Раса",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="start_permissions",
            field=models.JSONField(verbose_name="Навыки"),
        ),
        migrations.AlterField(
            model_name="race",
            name="start_points",
            field=models.JSONField(verbose_name="Стартовые характеристики"),
        ),
        migrations.AlterField(
            model_name="race",
            name="start_resistances",
            field=models.JSONField(verbose_name="Устойчивость"),
        ),
    ]
