# Generated by Django 4.1.3 on 2022-12-16 11:21

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0038_zone_alter_action_action_alias_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="zone",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="poll.person",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "region_description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
                ("x", models.IntegerField(blank=True, null=True)),
                ("y", models.IntegerField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poll.location"
                    ),
                ),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "db_table": "region",
                "ordering": ["region_name"],
                "managed": True,
            },
        ),
    ]
