# Generated by Django 4.1.3 on 2022-12-16 11:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0039_location_zone_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "district_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "district_description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
                ("x", models.IntegerField(blank=True, null=True)),
                ("y", models.IntegerField(blank=True, null=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poll.region"
                    ),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "db_table": "district",
                "ordering": ["district_name"],
                "managed": True,
            },
        ),
    ]
