# Generated by Django 4.1.3 on 2022-12-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0040_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="poll.zone"
            ),
        ),
    ]
