# Generated by Django 4.1.3 on 2022-12-17 22:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0042_alter_location_location_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={
                "managed": False,
                "ordering": ["region_name"],
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
            },
        ),
        migrations.AlterField(
            model_name="fraction",
            name="fraction_name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="location_name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="poll.zone",
                verbose_name="Зона",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="poll.owner",
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="zone_description",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="zone_name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Название"
            ),
        ),
    ]
