# Generated by Django 4.1.3 on 2022-12-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0043_alter_region_options_alter_fraction_fraction_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={
                "managed": True,
                "ordering": ["region_name"],
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
            },
        ),
    ]
