# Generated by Django 4.1.3 on 2022-12-18 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0044_alter_region_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={
                "managed": False,
                "ordering": ["region_name"],
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
            },
        ),
        migrations.RemoveField(model_name="location", name="zone",),
    ]
