# Generated by Django 4.1.3 on 2022-12-18 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0045_alter_region_options_remove_location_zone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={
                "managed": True,
                "ordering": ["region_name"],
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
            },
        ),
    ]
