# Generated by Django 4.1.3 on 2022-12-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0046_alter_region_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="zone",
            field=models.IntegerField(blank=True, null=True, verbose_name="Зона"),
        ),
        migrations.AlterField(
            model_name="region",
            name="location",
            field=models.IntegerField(blank=True, null=True, verbose_name="Локация"),
        ),
        migrations.AlterField(
            model_name="region",
            name="region_name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Название"
            ),
        ),
    ]
