# Generated by Django 4.1.3 on 2022-12-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0048_alter_owner_options_alter_person_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="column",
            field=models.IntegerField(blank=True, null=True, verbose_name="column"),
        ),
        migrations.AddField(
            model_name="region",
            name="coordinates",
            field=models.CharField(
                blank=True, max_length=14, null=True, verbose_name="Координаты"
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="fraction",
            field=models.IntegerField(blank=True, null=True, verbose_name="Фракция"),
        ),
        migrations.AddField(
            model_name="region",
            name="row",
            field=models.IntegerField(blank=True, null=True, verbose_name="row"),
        ),
        migrations.AlterField(
            model_name="region",
            name="x",
            field=models.IntegerField(blank=True, null=True, verbose_name="X"),
        ),
        migrations.AlterField(
            model_name="region",
            name="y",
            field=models.IntegerField(blank=True, null=True, verbose_name="Y"),
        ),
    ]
