# Generated by Django 4.1.3 on 2022-12-19 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0049_region_column_region_coordinates_region_fraction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="fraction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="poll.fraction",
                verbose_name="Фракция",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="poll.zone",
                verbose_name="Зона",
            ),
        ),
    ]
