# Generated by Django 4.1.3 on 2022-12-26 17:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0050_alter_region_fraction_alter_region_zone"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Тип действия",
                    ),
                ),
                (
                    "action_type_alias",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Алиас типа"
                    ),
                ),
                (
                    "action_type_description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Описание типа"
                    ),
                ),
            ],
            options={
                "verbose_name": "ActionType",
                "verbose_name_plural": "ActionTypes",
                "db_table": "action_type",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="action",
            name="duration",
            field=models.IntegerField(default=0, verbose_name="Срок"),
        ),
    ]
