# Generated by Django 4.1.3 on 2022-12-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0052_action_action_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="action", name="action_type",),
        migrations.AddField(
            model_name="action",
            name="action_type",
            field=models.ManyToManyField(blank=True, null=True, to="poll.actiontype"),
        ),
    ]
