# Generated by Django 4.1.3 on 2022-12-26 19:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0053_remove_action_action_type_action_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="region_description",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
    ]
