# Generated by Django 4.1.3 on 2022-12-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0054_alter_region_region_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="level",
            field=models.IntegerField(default=0, verbose_name="Уровень"),
        ),
        migrations.AddField(
            model_name="feature",
            name="level",
            field=models.IntegerField(default=0, verbose_name="Уровень"),
        ),
        migrations.AddField(
            model_name="personbar",
            name="fov",
            field=models.IntegerField(default=0, verbose_name="Область обзора"),
        ),
        migrations.AddField(
            model_name="personbar",
            name="level",
            field=models.IntegerField(default=0, verbose_name="Уровень"),
        ),
        migrations.AddField(
            model_name="personbar",
            name="rov",
            field=models.IntegerField(default=0, verbose_name="Дальность обзора"),
        ),
    ]
