# Generated by Django 4.1.3 on 2022-12-28 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0057_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="poll.location",
                verbose_name="Локация",
            ),
        ),
    ]
