# Generated by Django 4.1.3 on 2023-01-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0059_alter_owner_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="conditions_new",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Новые кондиции"
            ),
        ),
        migrations.AddField(
            model_name="history",
            name="conditions_old",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Прежние кондиции"
            ),
        ),
        migrations.AddField(
            model_name="personbar",
            name="conditions",
            field=models.JSONField(blank=True, null=True, verbose_name="Кондиции"),
        ),
    ]
