# Generated by Django 4.1.3 on 2023-01-05 09:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0060_history_conditions_new_history_conditions_old_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Safe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("safe_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "safe_description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "rental_price",
                    models.IntegerField(default=0, verbose_name="Уровень"),
                ),
                (
                    "consumables_sum_value",
                    models.IntegerField(default=0, verbose_name="Уровень"),
                ),
                (
                    "thing_sum_value",
                    models.IntegerField(default=0, verbose_name="Уровень"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poll.location"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poll.person"
                    ),
                ),
            ],
            options={
                "verbose_name": "Safe",
                "verbose_name_plural": "Safes",
                "db_table": "safe",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inventory_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "inventory_description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "inventory_max_weight",
                    models.IntegerField(default=0, verbose_name="Уровень"),
                ),
                (
                    "consumables_sum_value",
                    models.IntegerField(default=0, verbose_name="Уровень"),
                ),
                (
                    "thing_sum_value",
                    models.IntegerField(default=0, verbose_name="Уровень"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poll.person"
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory",
                "verbose_name_plural": "Inventories",
                "db_table": "inventory",
                "managed": True,
            },
        ),
    ]
