# Generated by Django 4.1.3 on 2023-01-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0062_alter_consumable_consumable_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="inventory", name="consumables_sum_value",),
        migrations.RemoveField(model_name="inventory", name="thing_sum_value",),
        migrations.RemoveField(model_name="safe", name="consumables_sum_value",),
        migrations.RemoveField(model_name="safe", name="thing_sum_value",),
        migrations.AddField(
            model_name="safe",
            name="max_weight",
            field=models.IntegerField(default=0, verbose_name="Максимальный вес"),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="inventory_max_weight",
            field=models.IntegerField(default=0, verbose_name="Максимальный вес"),
        ),
        migrations.AlterField(
            model_name="safe",
            name="rental_price",
            field=models.IntegerField(default=0, verbose_name="Стоимость аренды"),
        ),
    ]
