# Generated by Django 4.1.3 on 2023-01-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0063_remove_inventory_consumables_sum_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="consumables",
            field=models.ManyToManyField(
                blank=True, null=True, to="poll.consumable", verbose_name="Расходники"
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="things",
            field=models.ManyToManyField(
                blank=True, null=True, to="poll.thing", verbose_name="Артефакты"
            ),
        ),
        migrations.AddField(
            model_name="safe",
            name="consumables",
            field=models.ManyToManyField(
                blank=True, null=True, to="poll.consumable", verbose_name="Расходники"
            ),
        ),
        migrations.AddField(
            model_name="safe",
            name="things",
            field=models.ManyToManyField(
                blank=True, null=True, to="poll.thing", verbose_name="Артефакты"
            ),
        ),
    ]
