# Generated by Django 4.1.3 on 2023-01-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0064_inventory_consumables_inventory_things_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumable",
            name="weight",
            field=models.IntegerField(default=0, verbose_name="Вес"),
        ),
        migrations.AddField(
            model_name="thing",
            name="weight",
            field=models.IntegerField(default=0, verbose_name="Вес"),
        ),
    ]
