# Generated by Django 4.1.3 on 2023-01-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0065_consumable_weight_thing_weight"),
    ]

    operations = [
        migrations.RenameField(model_name="action", old_name="AP", new_name="ap",),
        migrations.RenameField(
            model_name="action", old_name="Bleed_access", new_name="bleed_access",
        ),
        migrations.RenameField(model_name="action", old_name="BP", new_name="bp",),
        migrations.RenameField(model_name="action", old_name="CP", new_name="cp",),
        migrations.RenameField(
            model_name="action", old_name="Crushing_access", new_name="crushing_access",
        ),
        migrations.RenameField(
            model_name="action", old_name="Curse_access", new_name="curse_access",
        ),
        migrations.RenameField(
            model_name="action", old_name="Cutting_access", new_name="cutting_access",
        ),
        migrations.RenameField(
            model_name="action", old_name="Dirt_access", new_name="dirt_access",
        ),
        migrations.RenameField(
            model_name="action", old_name="Fire_access", new_name="fire_access",
        ),
        migrations.RenameField(model_name="action", old_name="FP", new_name="fp",),
        migrations.RenameField(
            model_name="action", old_name="Holy_access", new_name="holy_access",
        ),
        migrations.RenameField(model_name="action", old_name="IP", new_name="ip",),
        migrations.RenameField(
            model_name="action",
            old_name="Lightning_access",
            new_name="lightning_access",
        ),
        migrations.RenameField(model_name="action", old_name="LP", new_name="lp",),
        migrations.RenameField(
            model_name="action", old_name="Mental_access", new_name="mental_access",
        ),
        migrations.RenameField(model_name="action", old_name="MP", new_name="mp",),
        migrations.RenameField(
            model_name="action", old_name="Nature_access", new_name="nature_access",
        ),
        migrations.RenameField(
            model_name="action",
            old_name="Onehanded_access",
            new_name="onehanded_access",
        ),
        migrations.RenameField(
            model_name="action", old_name="Polearm_access", new_name="polearm_access",
        ),
        migrations.RenameField(model_name="action", old_name="PP", new_name="pp",),
        migrations.RenameField(
            model_name="action", old_name="Shields_access", new_name="shields_access",
        ),
        migrations.RenameField(
            model_name="action",
            old_name="Small_arms_access",
            new_name="small_arms_access",
        ),
        migrations.RenameField(model_name="action", old_name="SP", new_name="sp",),
        migrations.RenameField(
            model_name="action", old_name="Stabbing_access", new_name="stabbing_access",
        ),
        migrations.RenameField(
            model_name="action",
            old_name="Twohanded_access",
            new_name="twohanded_access",
        ),
        migrations.RenameField(
            model_name="action", old_name="Water_access", new_name="water_access",
        ),
        migrations.RenameField(
            model_name="action", old_name="Wind_access", new_name="wind_access",
        ),
        migrations.RenameField(model_name="feature", old_name="AP", new_name="ap",),
        migrations.RenameField(
            model_name="feature", old_name="Bleed_access", new_name="bleed_access",
        ),
        migrations.RenameField(model_name="feature", old_name="BP", new_name="bp",),
        migrations.RenameField(model_name="feature", old_name="CP", new_name="cp",),
        migrations.RenameField(
            model_name="feature",
            old_name="Crushing_access",
            new_name="crushing_access",
        ),
        migrations.RenameField(
            model_name="feature", old_name="Curse_access", new_name="curse_access",
        ),
        migrations.RenameField(
            model_name="feature", old_name="Cutting_access", new_name="cutting_access",
        ),
        migrations.RenameField(
            model_name="feature", old_name="Dirt_access", new_name="dirt_access",
        ),
        migrations.RenameField(
            model_name="feature", old_name="Fire_access", new_name="fire_access",
        ),
        migrations.RenameField(model_name="feature", old_name="FP", new_name="fp",),
        migrations.RenameField(
            model_name="feature", old_name="Holy_access", new_name="holy_access",
        ),
        migrations.RenameField(model_name="feature", old_name="IP", new_name="ip",),
        migrations.RenameField(
            model_name="feature",
            old_name="Lightning_access",
            new_name="lightning_access",
        ),
        migrations.RenameField(model_name="feature", old_name="LP", new_name="lp",),
        migrations.RenameField(
            model_name="feature", old_name="Mental_access", new_name="mental_access",
        ),
        migrations.RenameField(model_name="feature", old_name="MP", new_name="mp",),
        migrations.RenameField(
            model_name="feature", old_name="Nature_access", new_name="nature_access",
        ),
        migrations.RenameField(
            model_name="feature",
            old_name="Onehanded_access",
            new_name="onehanded_access",
        ),
        migrations.RenameField(
            model_name="feature", old_name="Polearm_access", new_name="polearm_access",
        ),
        migrations.RenameField(model_name="feature", old_name="PP", new_name="pp",),
        migrations.RenameField(
            model_name="feature", old_name="Shields_access", new_name="shields_access",
        ),
        migrations.RenameField(
            model_name="feature",
            old_name="Small_arms_access",
            new_name="small_arms_access",
        ),
        migrations.RenameField(model_name="feature", old_name="SP", new_name="sp",),
        migrations.RenameField(
            model_name="feature",
            old_name="Stabbing_access",
            new_name="stabbing_access",
        ),
        migrations.RenameField(
            model_name="feature",
            old_name="Twohanded_access",
            new_name="twohanded_access",
        ),
        migrations.RenameField(
            model_name="feature", old_name="Water_access", new_name="water_access",
        ),
        migrations.RenameField(
            model_name="feature", old_name="Wind_access", new_name="wind_access",
        ),
        migrations.RemoveField(model_name="safe", name="max_weight",),
        migrations.AddField(
            model_name="safe",
            name="max_value",
            field=models.IntegerField(default=0, verbose_name="Максимальная стоимость"),
        ),
    ]
