# Generated by Django 4.1.3 on 2023-01-10 06:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0066_rename_ap_action_ap_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Money",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "money_type",
                    models.CharField(
                        choices=[
                            ("0", "Медь"),
                            ("1", "Серебро"),
                            ("2", "Золото"),
                            ("3", "Прочее"),
                        ],
                        default="0",
                        max_length=1,
                        verbose_name="Название",
                    ),
                ),
                ("weight", models.IntegerField(default=1, verbose_name="Вес")),
                ("rate", models.IntegerField(default=1, verbose_name="Номинал")),
            ],
            options={
                "verbose_name": "Money",
                "verbose_name_plural": "Money",
                "db_table": "money",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spell_name",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "spell_description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "points_to_use",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="очки характеристик для применения",
                    ),
                ),
                (
                    "permissions_from_use",
                    models.JSONField(
                        blank=True, null=True, verbose_name="очки навыков от применения"
                    ),
                ),
                (
                    "resistances_from_use",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="очки сопротивлений от применения",
                    ),
                ),
                (
                    "equipment_to_use",
                    models.JSONField(
                        blank=True, null=True, verbose_name="слоты для применения"
                    ),
                ),
                (
                    "points_from_use",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="очки характеристик от применения",
                    ),
                ),
                (
                    "equipment_from_use",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="расширение слотов от применения",
                    ),
                ),
                (
                    "damage_from_use",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="очки урона противнику от применения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spell",
                "verbose_name_plural": "Spells",
                "db_table": "spell",
                "managed": True,
            },
        ),
        migrations.AlterField(
            model_name="feature",
            name="feature_name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Название"
            ),
        ),
    ]
