# Generated by Django 4.1.3 on 2023-01-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0067_money_spell_alter_feature_feature_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="money",
            field=models.ManyToManyField(
                blank=True, null=True, to="poll.money", verbose_name="Ценности"
            ),
        ),
        migrations.AddField(
            model_name="safe",
            name="money",
            field=models.ManyToManyField(
                blank=True, null=True, to="poll.money", verbose_name="Ценности"
            ),
        ),
    ]
