# Generated by Django 4.1.3 on 2023-01-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0068_inventory_money_safe_money"),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="person",
            field=models.ManyToManyField(
                blank=True, null=True, to="poll.person", verbose_name="Персонаж"
            ),
        ),
    ]
