# Generated by Django 4.1.3 on 2023-01-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0071_alter_person_location_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="location_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_new",
                to="poll.location",
                verbose_name="Новая локация",
            ),
        ),
        migrations.AddField(
            model_name="history",
            name="location_old",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_old",
                to="poll.location",
                verbose_name="Прежняя локация",
            ),
        ),
    ]
