# Generated by Django 4.1.3 on 2023-01-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0073_alter_personlocation_location_personregion"),
    ]

    operations = [
        migrations.RemoveField(model_name="spell", name="equipment_to_use",),
        migrations.RemoveField(model_name="spell", name="points_to_use",),
        migrations.AddField(
            model_name="spell",
            name="conditions_from_use",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Прирост кондиций"
            ),
        ),
        migrations.AddField(
            model_name="spell",
            name="consumable",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Артефакты для использования"
            ),
        ),
        migrations.AddField(
            model_name="spell",
            name="permissions_to_use",
            field=models.JSONField(
                blank=True, null=True, verbose_name="очки навыков для применения"
            ),
        ),
        migrations.AddField(
            model_name="spell",
            name="thing",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Артефакты для использования"
            ),
        ),
    ]
