# Generated by Django 4.1.3 on 2023-01-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0074_remove_spell_equipment_to_use_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="consumable_list",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="Список Расходников для использования",
            ),
        ),
        migrations.AddField(
            model_name="spell",
            name="thing_list",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="Список Артефактов для использования",
            ),
        ),
        migrations.RemoveField(model_name="spell", name="consumable",),
        migrations.RemoveField(model_name="spell", name="thing",),
        migrations.AddField(
            model_name="spell",
            name="consumable",
            field=models.ManyToManyField(
                blank=True, null=True, to="poll.consumable", verbose_name="Расходники"
            ),
        ),
        migrations.AddField(
            model_name="spell",
            name="thing",
            field=models.ManyToManyField(
                blank=True, null=True, to="poll.thing", verbose_name="Артефакты"
            ),
        ),
    ]
