# Generated by Django 4.1.3 on 2023-01-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0075_spell_consumable_list_spell_thing_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="agg_points",
            field=models.IntegerField(default=0, verbose_name="Агрегированные очки"),
        ),
    ]
