# Generated by Django 4.1.3 on 2023-01-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0076_alter_feature_agg_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="features",
            field=models.ManyToManyField(to="poll.feature"),
        ),
    ]
