# Generated by Django 4.1.3 on 2023-01-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0077_alter_person_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="action_type",
            field=models.ManyToManyField(to="poll.actiontype"),
        ),
        migrations.AlterField(
            model_name="history",
            name="action_type",
            field=models.ManyToManyField(
                to="poll.actiontype", verbose_name="тип действия Персонажа"
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="consumables",
            field=models.ManyToManyField(
                to="poll.consumable", verbose_name="Расходники"
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="money",
            field=models.ManyToManyField(to="poll.money", verbose_name="Ценности"),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="things",
            field=models.ManyToManyField(to="poll.thing", verbose_name="Артефакты"),
        ),
        migrations.AlterField(
            model_name="safe",
            name="consumables",
            field=models.ManyToManyField(
                to="poll.consumable", verbose_name="Расходники"
            ),
        ),
        migrations.AlterField(
            model_name="safe",
            name="money",
            field=models.ManyToManyField(to="poll.money", verbose_name="Ценности"),
        ),
        migrations.AlterField(
            model_name="safe",
            name="things",
            field=models.ManyToManyField(to="poll.thing", verbose_name="Артефакты"),
        ),
        migrations.AlterField(
            model_name="spell",
            name="consumable",
            field=models.ManyToManyField(
                to="poll.consumable", verbose_name="Расходники"
            ),
        ),
        migrations.AlterField(
            model_name="spell",
            name="person",
            field=models.ManyToManyField(to="poll.person", verbose_name="Персонаж"),
        ),
        migrations.AlterField(
            model_name="spell",
            name="thing",
            field=models.ManyToManyField(to="poll.thing", verbose_name="Артефакты"),
        ),
    ]
