# Generated by Django 4.1.3 on 2023-01-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0079_alter_owner_owner_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumable",
            name="buy_price",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Цена покупки"
            ),
        ),
        migrations.AlterField(
            model_name="consumable",
            name="sale_price",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Цена продажи"
            ),
        ),
        migrations.AlterField(
            model_name="consumable",
            name="weight",
            field=models.IntegerField(blank=True, null=True, verbose_name="Вес"),
        ),
    ]
