# Generated by Django 4.1.3 on 2023-01-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0081_consumable_ap_from_use_consumable_ap_to_make_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumable",
            name="clean_damage",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="чистый урон"
            ),
        ),
        migrations.AddField(
            model_name="thing",
            name="clean_damage",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="чистый урон"
            ),
        ),
    ]
